# Generated by Django 5.2 on 2025-04-08 12:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('ngo', 'NGO'), ('food_banks', 'Food Banks'), ('community_kitchen', 'Community Kitchen'), ('consumer', 'Consumer'), ('logistics', 'Logistics'), ('food_banks_ngo_community_kitchen', 'Food Banks | NGO | Community Kitchen')], default='consumer', max_length=60)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(help_text='Phone number or email', max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_hours', models.CharField(choices=[('weekdays', 'Monday to Friday: 8:00 AM - 5:00 PM'), ('saturday', 'Saturday: 9:00 AM - 1:00 PM'), ('sunday_closed', 'Sunday: Closed')], default='weekdays', max_length=50)),
                ('certification', models.FileField(blank=True, null=True, upload_to='document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'docx'])])),
                ('product_type', models.TextField(blank=True, help_text='e.g vegetables, cereals, legumes, fruits', null=True)),
                ('typical_quantity', models.CharField(choices=[('0 - 50 kg', '0 to 50 kilograms'), ('60 - 100 kg', '60 to 100 kilograms'), ('110 - 150 kg', '110 to 150 kilograms')], default='0 - 50 kg', max_length=255)),
                ('order_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=255)),
                ('logistics_availability', models.BooleanField(default=True)),
                ('Additional_Information', models.TextField(blank=True, help_text='e.g core values, primary mission, operation area', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CommunityKitchen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community-Kitchen Profile',
                'verbose_name_plural': 'Community-Kitchen Profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('location', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('crops_grown', models.TextField(help_text='e.g. maize, tomatoes, onions')),
                ('average_harvest', models.CharField(max_length=255)),
                ('has_storage', models.BooleanField(default=False)),
                ('available_for_donation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer data',
                'verbose_name_plural': 'Farmers data',
                'ordering': ['farm_name'],
            },
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(help_text='Phone number or email', max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_hours', models.CharField(choices=[('weekdays', 'Monday to Friday: 8:00 AM - 5:00 PM'), ('saturday', 'Saturday: 9:00 AM - 1:00 PM'), ('sunday_closed', 'Sunday: Closed')], default='weekdays', max_length=50)),
                ('certification', models.FileField(blank=True, null=True, upload_to='document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'docx'])])),
                ('product_type', models.TextField(blank=True, help_text='e.g vegetables, cereals, legumes, fruits', null=True)),
                ('typical_quantity', models.CharField(choices=[('0 - 50 kg', '0 to 50 kilograms'), ('60 - 100 kg', '60 to 100 kilograms'), ('110 - 150 kg', '110 to 150 kilograms')], default='0 - 50 kg', max_length=255)),
                ('order_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=255)),
                ('logistics_availability', models.BooleanField(default=True)),
                ('Additional_Information', models.TextField(blank=True, help_text='e.g core values, primary mission, operation area', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FoodBank_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FoodBank Profile',
                'verbose_name_plural': 'FoodBank Profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(help_text='Phone number or email', max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_hours', models.CharField(choices=[('weekdays', 'Monday to Friday: 8:00 AM - 5:00 PM'), ('saturday', 'Saturday: 9:00 AM - 1:00 PM'), ('sunday_closed', 'Sunday: Closed')], default='weekdays', max_length=50)),
                ('certification', models.FileField(blank=True, null=True, upload_to='document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'docx'])])),
                ('product_type', models.TextField(blank=True, help_text='e.g vegetables, cereals, legumes, fruits', null=True)),
                ('typical_quantity', models.CharField(choices=[('0 - 50 kg', '0 to 50 kilograms'), ('60 - 100 kg', '60 to 100 kilograms'), ('110 - 150 kg', '110 to 150 kilograms')], default='0 - 50 kg', max_length=255)),
                ('order_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=255)),
                ('logistics_availability', models.BooleanField(default=True)),
                ('Additional_Information', models.TextField(blank=True, help_text='e.g core values, primary mission, operation area', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NGO Profile',
                'verbose_name_plural': 'NGO Profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(help_text='e.g. vegetable, grain, fruit', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kilograms or relevant unit', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_account_app.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Product',
                'verbose_name_plural': 'Farmer Products',
                'ordering': ['name'],
            },
        ),
    ]
