# Generated by Django 5.2 on 2025-04-13 20:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('FARMER', 'Farmer'), ('CONSUMER', 'Consumer'), ('FOODBANK', 'Foodbank'), ('LOGISTICS', 'Logistics')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerSignup',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
                'ordering': ['country'],
                'proxy': False,
            },
            bases=('user_accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfileEdit',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.TextField(help_text='start with country code')),
                ('age', models.PositiveIntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('years_farming', models.CharField(help_text='e.g 4 years, 4 weeks, or 4 months', max_length=50)),
                ('location', models.CharField(help_text='Country, City', max_length=255)),
                ('farm_size', models.CharField(help_text='e.g 3 Acres', max_length=50)),
                ('type_of_farming', models.CharField(help_text='e.g. list all farming types practiced', max_length=255)),
                ('crops_grown', models.CharField(help_text='list all crops grown', max_length=255)),
                ('livestock', models.CharField(help_text='e.g. sheep, poultry, cattle', max_length=255)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['location'],
                'proxy': False,
            },
            bases=('user_accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodbankSignup',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foodbank',
                'verbose_name_plural': 'Foodbanks',
                'ordering': ['country'],
                'proxy': False,
            },
            bases=('user_accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsSignup',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Logistics',
                'verbose_name_plural': 'Logistics',
                'ordering': ['country'],
                'proxy': False,
            },
            bases=('user_accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(blank=True, max_length=255, null=True)),
                ('produce_type', models.CharField(help_text='e.g. cereal, legumes, tubers, fruits, vegetables, etc', max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='prduce_images/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter price in your local currency, e.g $9.99', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Enter quantity in grams or kilograms (e.g. 2.5 kg, 3 g)', max_digits=10)),
                ('harvest_date', models.DateField(blank=True, help_text='Enter harvest date (DD/MM/YYYY)', null=True)),
                ('stock_availability', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
                'ordering': ['produce_name'],
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerProfileModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['full_name'],
                'proxy': False,
            },
            bases=('user_accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
